version: "3.9"

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:13.2-alpine
    container_name: kong-db
    restart: always
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - ./cache-kong-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
    networks:
      - kong-net
  kong-migration:
    image: kong/kong-gateway:2.3.3.2-alpine
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_PASSWORD=kong
      - KONG_PLUGINS=bundled,custom-plugin
    links:
      - kong-database
    depends_on:
      - kong-database
    networks:
      - kong-net
  api-gateway:
    image: kong/kong-gateway:2.3.3.2-alpine
    container_name: kong-ee
    restart: always
    links:
      - kong-database
    depends_on:
      kong-migration:
        condition: service_started
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
      - KONG_PLUGINS=bundled,custom-plugin
      # - KONG_NGINX_PROXY_GZIP=on
      # - KONG_NGINX_PROXY_GZIP_TYPES="text/plain application/json"
    ports:
      - "8000-8004:8000-8004"
      - "8443-8445:8443-8445"
    volumes:
      - ./custom-plugin:/usr/local/share/lua/5.1/kong/plugins/custom-plugin
    networks:
      - kong-net
